# Final project: Board game recommender

In [43]:
# import libraries
import pandas as pd
import numpy as np
import scipy.stats as st

pd.set_option("display.max_columns", 0) #no limit to cols we want to see

In [142]:
# import datasets from boardgamegeek
categories = pd.read_csv('./csv_files/bgg_Category.csv')
game_families = pd.read_csv('./csv_files/bgg_GameFamily.csv')
game_items = pd.read_csv('./csv_files/bgg_GameItem.csv')
game_types = pd.read_csv('./csv_files/bgg_GameType.csv')
mechanics = pd.read_csv('./csv_files/bgg_Mechanic.csv')
authors = pd.read_csv('./csv_files/bgg_Person.csv')
publishers = pd.read_csv('./csv_files/bgg_Publisher.csv')

In [38]:
game_items.head(50)

    bgg_id                                    name  ...  wikidata_id wikipedia_id
0        1                              Die Macher  ...          NaN          NaN
1        2                            Dragonmaster  ...          NaN          NaN
2        3                                 Samurai  ...          NaN          NaN
3        4                          Tal der KÃ¶nige  ...          NaN          NaN
4        5                                 Acquire  ...          NaN          NaN
5        6                      Mare Mediterraneum  ...          NaN          NaN
6        7                               Cathedral  ...          NaN          NaN
7        8                       Lords of Creation  ...          NaN          NaN
8        9                            El Caballero  ...          NaN          NaN
9       10                               Elfenland  ...          NaN          NaN
10      11                                Bohnanza  ...          NaN          NaN
11      12                                      Ra  ...          NaN          NaN
12      13                                   CATAN  ...          NaN          NaN
13      14                                  Basari  ...          NaN          NaN
14      15                        Cosmic Encounter  ...          NaN          NaN
15      16                               MarraCash  ...          NaN          NaN
16      17                              Button Men  ...          NaN          NaN
17      18                               RoboRally  ...          NaN          NaN
18      19                        Wacky Wacky West  ...          NaN          NaN
19      20                      Full Metal PlanÃ¨te  ...          NaN          NaN
20      21                    Gateway to the Stars  ...          NaN          NaN
21      22                             Magic Realm  ...          NaN          NaN
22      23                            Divine Right  ...          NaN          NaN
23      24                       Twilight Imperium  ...          NaN          NaN
24      25                              Battlemist  ...          NaN          NaN
25      26                      Age of Renaissance  ...          NaN          NaN
26      27  Supremacy: The Game of the Superpowers  ...          NaN          NaN
27      28                              Illuminati  ...          NaN          NaN
28      29                           Terrain Vague  ...          NaN          NaN
29      30                              Dark Tower  ...          NaN          NaN
30      31                              Dark World  ...          NaN          NaN
31      32                           Buffalo Chess  ...          NaN          NaN
32      34                           Arkham Horror  ...          NaN          NaN
33      36                     Federation & Empire  ...          NaN          NaN
34      37                          Dragon Masters  ...          NaN          NaN
35      38                                   Runes  ...          NaN          NaN
36      39                                Darkover  ...          NaN          NaN
37      40                             Borderlands  ...          NaN          NaN
38      41                              Can't Stop  ...          NaN          NaN
39      42                      Tigris & Euphrates  ...          NaN          NaN
40      43                                Airlines  ...          NaN          NaN
41      44                         David & Goliath  ...          NaN          NaN
42      45                                  Perudo  ...          NaN          NaN
43      46                                  Medici  ...          NaN          NaN
44      47                               Chinatown  ...          NaN          NaN
45      48                       Krieg und Frieden  ...          NaN          NaN
46      49                              Mamma Mia!  ...          NaN          NaN
47      50                             Lost Cities  ...          NaN          NaN
48      51                         Ricochet Robots  ...          NaN          NaN
49      52                          Mighty Empires  ...          NaN          NaN

[50 rows x 38 columns]

BoardGameGeek is our major target for information regarding the board games. It is a community-run database that includes user rankings and recommendations based on number of players: time to beat/finish: category: mechanics of game: etc. Each major filter is divided by dataframe that converges/is IDd in `game_items`: and we will now asess them.

In [20]:
# reviewing categories - 84
display(categories.head(40))
display(categories.tail(44))

    bgg_id                     name
0     1001                Political
1     1002                Card Game
2     1008                 Nautical
3     1009        Abstract Strategy
4     1010                  Fantasy
5     1011           Transportation
6     1013                  Farming
7     1015             Civilization
8     1016          Science Fiction
9     1017                     Dice
10    1019                  Wargame
11    1020              Exploration
12    1021                 Economic
13    1022                Adventure
14    1023                 Bluffing
15    1024                   Horror
16    1025                Word Game
17    1026              Negotiation
18    1027                   Trivia
19    1028                   Puzzle
20    1029            City Building
21    1030               Party Game
22    1031                   Racing
23    1032       Action / Dexterity
24    1033                    Mafia
25    1034                   Trains
26    1035                 Medieval
27    1036              Prehistoric
28    1037                Real-time
29    1038                   Sports
30    1039                Deduction
31    1040           Murder/Mystery
32    1041          Children's Game
33    1042  Expansion for Base-game
34    1044   Collectible Components
35    1045                   Memory
36    1046                 Fighting
37    1047               Miniatures
38    1048       American Civil War
39    1049             World War II

    bgg_id                        name
40    1050                     Ancient
41    1051                  Napoleonic
42    1052                     Arabian
43    1054                       Music
44    1055               American West
45    1059                        Maze
46    1064   Movies / TV / Radio theme
47    1065                 World War I
48    1069              Modern Warfare
49    1070                 Renaissance
50    1072                  Electronic
51    1075  American Revolutionary War
52    1079                       Humor
53    1081         Spies/Secret Agents
54    1082                   Mythology
55    1084               Environmental
56    1086          Territory Building
57    1088    Industry / Manufacturing
58    1089                     Animals
59    1090                     Pirates
60    1091                  Korean War
61    1093                 Novel-based
62    1094                 Educational
63    1097                      Travel
64    1098                      Number
65    1101            Video Game Theme
66    1102                   Civil War
67    1104                        Math
68    1108        American Indian Wars
69    1109                 Vietnam War
70    1113           Space Exploration
71    1115                   Religious
72    1116          Comic Book / Strip
73    1117                        Book
74    1118              Mature / Adult
75    1119                 Game System
76    1120                Print & Play
77    2145                     Medical
78    2481                     Zombies
79    2650           Aviation / Flight
80    2687               Fan Expansion
81    2710             Post-Napoleonic
82    2725               Pike and Shot
83    2726               Age of Reason

`Categories` show the genre of the game: or the theme that it will set in.

In [22]:
# reviewing mechanics - 191
display(mechanics.head(60))
display(mechanics.tail(60))

    bgg_id                                name
0     2001                       Action Points
1     2002                      Tile Placement
2     2003                 Rock-Paper-Scissors
3     2004                      Set Collection
4     2005                       Stock Holding
5     2007                 Pick-up and Deliver
6     2008                             Trading
7     2009                        Trick-taking
8     2010                  Crayon Rail System
9     2011                       Modular Board
10    2012                     Auction/Bidding
11    2013               Commodity Speculation
12    2014                Betting and Bluffing
13    2015              Variable Player Powers
14    2016              Secret Unit Deployment
15    2017                              Voting
16    2018       Campaign / Battle Card Driven
17    2019                     Team-Based Game
18    2020       Simultaneous Action Selection
19    2021                        Area-Impulse
20    2023                    Cooperative Game
21    2026                        Hexagon Grid
22    2027                        Storytelling
23    2028                        Role Playing
24    2035                Roll / Spin and Move
25    2038                             Singing
26    2039                        Line Drawing
27    2040                     Hand Management
28    2041                       Open Drafting
29    2043                           Enclosure
30    2046                       Area Movement
31    2047                              Memory
32    2048                    Pattern Building
33    2055                    Paper-and-Pencil
34    2057                    Chit-Pull System
35    2060                 Pattern Recognition
36    2070                          Simulation
37    2072                        Dice Rolling
38    2073                              Acting
39    2078             Point to Point Movement
40    2079                Variable Phase Order
41    2080           Area Majority / Influence
42    2081          Network and Route Building
43    2082                    Worker Placement
44    2661                      Push Your Luck
45    2663              Turn Order: Time Track
46    2664        Deck, Bag, and Pool Building
47    2676                       Grid Movement
48    2685                  Player Elimination
49    2686                           Take That
50    2689                        Action Queue
51    2813                              Rondel
52    2814                        Traitor Game
53    2819               Solo / Solitaire Game
54    2820               Semi-Cooperative Game
55    2821                   Single Loser Game
56    2822  Scenario / Mission / Campaign Game
57    2823                Score-and-Reset Game
58    2824                         Legacy Game
59    2826              Turn Order: Stat-Based

     bgg_id                                      name
131    2927                     Auction: Multiple Lot
132    2928                    Closed Economy Auction
133    2930                        Auction: Dexterity
134    2931                  Auction: Fixed Placement
135    2932                   Auction: Dutch Priority
136    2933  Worker Placement, Different Worker Types
137    2935        Worker Placement with Dice Workers
138    2939                            Track Movement
139    2940                               Square Grid
140    2944                Three Dimensional Movement
141    2946                          Pattern Movement
142    2947                           Movement Points
143    2948                          Resource to Move
144    2949                      Measurement Movement
145    2950                   Different Dice Movement
146    2952                          Impulse Movement
147    2953                       Programmed Movement
148    2954                         Relative Movement
149    2955                                   Mancala
150    2956                                  Chaining
151    2957                                      Bias
152    2958                     Moving Multiple Units
153    2959                              Map Addition
154    2960                             Map Reduction
155    2961                           Map Deformation
156    2962                         Move Through Deck
157    2963                         Movement Template
158    2964                             Pieces as Map
159    2965                             Multiple Maps
160    2967                           Hidden Movement
161    2974                           Zone of Control
162    2975                             Line of Sight
163    2978                             Grid Coverage
164    2980                           Ladder Climbing
165    2981                      Melding and Splaying
166    2984                           Closed Drafting
167    2985                        Turn Order: Random
168    2987                     Hidden Victory Points
169    2988                    Stacking and Balancing
170    2989                          Physical Removal
171    2990                                Cube Tower
172    2991                            Speed Matching
173    2999                                     Bingo
174    3000                                Hot Potato
175    3001                                  Layering
176    3002                                 Deduction
177    3003                                 Induction
178    3004                         Deck Construction
179    3005                                Slide/Push
180    3006                            Predictive Bid
181    3007                                  Matching
182    3096                                   Drawing
183    3097                            Bids As Wagers
184    3098                      Auction Compensation
185    3099                           Multi-Use Cards
186    3100                                      Tags
187    3101                                  Ordering
188    3102                     Questions and Answers
189    3103                            Resource Queue
190    3104                            Neighbor Scope

`Mechanics` deals with specific approach to the game that will be the main way of playing: or give insight to what tools might be needed to play a round.

In [23]:
# reviewing game types - 12
game_types

    bgg_id             name
0     4415            Amiga
1     4420     Commodore 64
2     4664         War Game
3     4665  Children's Game
4     4666    Abstract Game
5     4667     Customizable
6     4781           Arcade
7     4976         Atari ST
8     5496         Thematic
9     5497    Strategy Game
10    5498       Party Game
11    5499      Family Game

`game_types` are a broader type of category: that can encapsulate the audience it is meant for.

In [24]:
# reviewing game_families - 4828
game_families

      bgg_id                                          name
0          1                            Admin: Test Family
1          2                             Game: Carcassonne
2          3                                   Game: Catan
3          4            Series: The Chicken Family of Zoch
4          5                                Game: Bohnanza
...      ...                                           ...
4823   80388  Series: Evolution of Airpower in World War 2
4824   80397   Series: Air War Book Games (Historic Wings)
4825   80399            Video Game Theme: Assassin's Creed
4826   80400           Video Game Theme: The Elder Scrolls
4827   80408   Digital Implementations: Boardible (Mobile)

[4828 rows x 2 columns]

In [26]:
# reviewing game_items - 113904
game_items.isna().sum()

bgg_id                      0
name                        0
year                     9685
game_type               88074
designer                18251
artist                  66032
publisher                  52
min_players              1938
max_players              5456
min_players_rec          1938
max_players_rec          5456
min_players_best         1938
max_players_best         5456
min_age                 23263
min_age_rec            112778
min_time                22562
max_time                22562
category                 2214
mechanic                16767
cooperative            107550
compilation            112989
compilation_of         112989
family                  34859
implementation         108039
integration            109784
rank                    89425
num_votes               27722
avg_rating              27722
stddev_rating           45407
bayes_rating            88970
complexity              65614
language_dependency    113050
bga_id                 113904
dbpedia_id             113904
luding_id              113904
spielen_id             113904
wikidata_id            113904
wikipedia_id           113904
dtype: int64

In [120]:
game_items.head(30)

    bgg_id                                    name  ...  wikidata_id wikipedia_id
0        1                              Die Macher  ...          NaN          NaN
1        2                            Dragonmaster  ...          NaN          NaN
2        3                                 Samurai  ...          NaN          NaN
3        4                          Tal der KÃ¶nige  ...          NaN          NaN
4        5                                 Acquire  ...          NaN          NaN
5        6                      Mare Mediterraneum  ...          NaN          NaN
6        7                               Cathedral  ...          NaN          NaN
7        8                       Lords of Creation  ...          NaN          NaN
8        9                            El Caballero  ...          NaN          NaN
9       10                               Elfenland  ...          NaN          NaN
10      11                                Bohnanza  ...          NaN          NaN
11      12                                      Ra  ...          NaN          NaN
12      13                                   CATAN  ...          NaN          NaN
13      14                                  Basari  ...          NaN          NaN
14      15                        Cosmic Encounter  ...          NaN          NaN
15      16                               MarraCash  ...          NaN          NaN
16      17                              Button Men  ...          NaN          NaN
17      18                               RoboRally  ...          NaN          NaN
18      19                        Wacky Wacky West  ...          NaN          NaN
19      20                      Full Metal PlanÃ¨te  ...          NaN          NaN
20      21                    Gateway to the Stars  ...          NaN          NaN
21      22                             Magic Realm  ...          NaN          NaN
22      23                            Divine Right  ...          NaN          NaN
23      24                       Twilight Imperium  ...          NaN          NaN
24      25                              Battlemist  ...          NaN          NaN
25      26                      Age of Renaissance  ...          NaN          NaN
26      27  Supremacy: The Game of the Superpowers  ...          NaN          NaN
27      28                              Illuminati  ...          NaN          NaN
28      29                           Terrain Vague  ...          NaN          NaN
29      30                              Dark Tower  ...          NaN          NaN

[30 rows x 38 columns]

### Columns description:
- `bgg_id`: unique ID per board game; int.
- `name`: name of game; object.
- `year`: year of release; float.
- `game_type`: in-site's rough partition of game genres. Curently there are:
    - Uncategorized
    - Abstract Strategy Games (like Chess or Go)
    - Customizable Games (CCGs, CMGs, LCGs, etc.)
    - Thematic Games (emphasis on narrative)
    - Family Games (fun for kids and adults)
    - Children's Party Games (best for younger kids)
    - Strategy Games (more complex games)
    - Wargames (conflict simulation, etc.)
- `designer`:
- `artist`:
- `publisher`:
- `min_players`: minimum of players by manufacturer; float.
- `max_players`: maximum of players by manufacturer; float.
- `min_players_rec`: minimum of players by the community; float.
- `max_players_rec`: maximum of players by the community; float.
- `min_players_best`: best minimum of players by the community; float.
- `max_players_best`: best maximum of players by the community; float.
- `min_age`: required minimum age to play; float.
- `min_age_rec`: required minimum age to play recommended by community; float.
- `min_time`: minimum gameplay time, measured in minutes; float.
- `max_time`: maximum gameplay time, measured in minutes; float.
- `category`: additional grouping approach based on like subjects or similar characteristics; object.
- `mechanic`: metaphorical term referring to a functional aspect of a game; object.
- `cooperative`: ; float.
- `compilation`: boolean confirming whether it's part of a compilation of games; float.
- `compilation_of`:
- `family`:
- `implementation`:
- `integration`:
- `rank`:
- `num_votes`:
- `avg_rating`:
- `stddev_rating`:
- `bayes_rating`:
- `complexity`: measure of difficulty of the gameplay between 1 and 5; float. 
- `language_dependency`: measure of how much text and other language dependencies appear on a game's components or during gameplay between 1 and 5; float. 
- `bga_id`:
- `dbpedia_id`:
- `luding_id`:
- `spielen_id`:
- `wikidata_id`:
- `wikipedia_id`:

### Columns to keep for mvp:
- `bgg_id`:
- `name`:
- `year`:
- `designer`:
- `publisher`:
- `game_type`: in-site's rough partition of game genres (currently 8); object. *
- `min_time`: minimum gameplay time, measured in minutes; float. *
- `max_time`:
- `min_age`:
- `min_players`: minimum of players by manufacturer; float. *
- `max_players`: 
- `category`: additional grouping approach based on like subjects or similar characteristics; object. *
- `mechanic`: metaphorical term referring to a functional aspect of a game; object. *
- `complexity`: measure of difficulty of the gameplay between 1 and 5; float. *
- `language_dependency`: measure of how much text and other language dependencies appear on a game's components or during gameplay between 1 and 5; float. *
- `avg_rating`: TBD
- `rank`: TBD 
### Columns to drop:
- `artist`:
- `min_players_rec`: 
- `max_players_rec`: 
- `min_players_best`:
- `max_players_best`: 
- `min_age_rec`:
- `family`:
- `implementation`:
- `integration`:
- `cooperative`: 
- `compilation`: 
- `compilation_of`:
- `num_votes`:
- `stddev_rating`:
- `bayes_rating`:
- `bga_id`:
- `dbpedia_id`:
- `luding_id`:
- `spielen_id`:
- `wikidata_id`:
- `wikipedia_id`:

In [155]:
# drop cols that we don't need from game_items
game_items.drop([
    'artist', 'min_players_rec','max_players_rec', 'min_players_best', 'max_players_best', 
    'min_age_rec', 'cooperative', 'compilation', 'compilation_of', 'family',
    'implementation', 'integration', 'num_votes','stddev_rating', 'bayes_rating', 
    'bga_id', 'dbpedia_id', 'luding_id', 'spielen_id', 'wikidata_id', 'wikipedia_id'],
    axis = 1, inplace = True)

In [156]:
game_items
game_items.isna().sum()

bgg_id                      0
name                        0
year                     9685
game_type               88074
designer                18251
publisher                  52
min_players              1938
max_players              5456
min_age                 23263
min_time                22562
max_time                22562
category                 2214
mechanic                16767
rank                    89425
avg_rating              27722
complexity              65614
language_dependency    113050
dtype: int64

In [159]:
# assess nans in language_dep
test = round(game_items.language_dependency)
test.value_counts(dropna=False)

NaN    113050
1.0       400
4.0       149
2.0       146
3.0       144
5.0        15
Name: language_dependency, dtype: int64

There are too many nans in `language_dependency` to be useful, so it will be dropped.

In [161]:
game_items[game_items.name == 'Azul']

       bgg_id  name    year  ... avg_rating complexity language_dependency
77576  230802  Azul  2017.0  ...    7.76172     1.7613                 1.0

[1 rows x 17 columns]

In [160]:
game_items[game_items['language_dependency'].isna()]

        bgg_id                           name  ...  complexity language_dependency
1            2                   Dragonmaster  ...      1.9636                 NaN
3            4                 Tal der KÃ¶nige  ...      2.6667                 NaN
5            6             Mare Mediterraneum  ...      3.0000                 NaN
6            7                      Cathedral  ...      1.7872                 NaN
7            8              Lords of Creation  ...      2.4000                 NaN
...        ...                            ...  ...         ...                 ...
113899  391565                     Champions!  ...         NaN                 NaN
113900  391715           Leitin aÃ° stjÃ¶rnunni  ...         NaN                 NaN
113901  391720  The String Railway Collection  ...         NaN                 NaN
113902  391834                      SpellBook  ...         NaN                 NaN
113903  392146            Nightmares of Sushi  ...         NaN                 NaN

[113050 rows x 17 columns]

Qs:
1. Do these qualify as features? they're from the manufacturer so everyone is subjected to them 
2. what's wrong with the code below? 
3. Should i keep catgs/mechanics/game types exploded or joined?

In [123]:
game_items.category.fillna('', inplace = True)

In [129]:
# try exploding
d = categories.astype(str).set_index('bgg_id')['name']

# game_items['category'] = (
#     game_items['category'].str.split(',').explode().map(d).groupby(level=0).agg(','.join)
# )
game_items.category

0              1021,1026,1001
1                   1002,1010
2                   1009,1035
3                        1050
4                   1021,1086
                 ...
113899                   1030
113900    1041,1064,1030,1027
113901              1086,1034
113902                   1010
113903         1002,1039,1079
Name: category, Length: 113904, dtype: object

In [151]:
# game_items['category'] = game_items['category'].str.split(',').explode().map(d).groupby(level=0).agg(list)
col_list = ['category', 'mechanic', 'game_type']
df_list = [categories, mechanics, game_types]

def populate_dfs(df, col):
    game_items.fillna('', inplace = True)
    d = df.astype(str).set_index('bgg_id')['name']
    game_items[col] = game_items[col].str.split(',').explode().map(d).groupby(level=0).agg(list)
    return game_items[col]

In [72]:
# check crosstab between categories and mechanics
data_crosstab = pd.crosstab(game_items.category, game_items.mechanic, margins=False)
data_crosstab

AttributeError: 'DataFrame' object has no attribute 'categories'